  
language: generic
sudo: required 
services:
  - docker 

before_install: 
  - docker build -t sameem206/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true sameem206/react-test npm test

after_success:
  - docker build -t sameem206/fib-client ./client 
  - docker build -t sameem206/fib-nginx ./nginx
  - docker build -t sameem206/fib-server ./server
  - docker build -t sameem206/fib-worker ./worker 
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sameem206/fib-client 
  - docker push sameem206/fib-nginx
  - docker push sameem206/fib-server
  - docker push sameem206/fib-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'fib-services'
  env: 'Fibservices-env'
  bucket_name: 'elasticbeanstalk-us-west-2-641758240141'
  bucket_path: 'fib-services'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY